import { useState, type FC } from 'react'
import { FileTextIcon } from '@repo/icons/file-text'
import { FolderClosedIcon } from '@repo/icons/folder-closed-icon'
import { Button } from '@repo/ui/button'
import { Skeleton } from '@repo/ui/skeleton'
import { SectionLabel } from '../section-label'
import { VISIBLE_FILES } from '../../constants'
import { useWorkspaceFiles } from '../../hooks/use-workspace-files'

interface FilesSectionProps {
  profile: string
  displayName: string
}

/**
 * What is in this employee's workspace, newest first.
 *
 * Real data, from `GET /api/files` pointed at `<profile.path>/workspace` — see
 * `use-workspace-files` for why the path has to be assembled here rather than passed as a
 * `profile` parameter.
 *
 * What the design asks for and the backend has no answer to is *attribution*: nothing in
 * the managed-files payload says which employee, session or turn wrote a file, and Hermes
 * keeps no authorship index to join against. The directory is the whole of the claim being
 * made, so the section says "workspace" rather than "generated by" and the empty state says
 * the same.
 *
 * "See all" expands the list in place. There is no files route in this app to send anyone
 * to, and a link that navigated out of the modal would lose the thread behind it.
 */
export const FilesSection: FC<FilesSectionProps> = ({ profile, displayName }) => {
  const { files, isLoading, error } = useWorkspaceFiles(profile)
  const [expanded, setExpanded] = useState(false)

  const shown = expanded ? files : files.slice(0, VISIBLE_FILES)
  const hidden = files.length - shown.length

  return (
    <section aria-label="Files" className="flex flex-col gap-1">
      <SectionLabel
        action={
          hidden > 0 || expanded ? (
            <Button
              type="button"
              variant="link-secondary"
              size="xs"
              onClick={() => setExpanded((on) => !on)}
            >
              {expanded ? 'Show less' : `See all ${files.length}`}
            </Button>
          ) : undefined
        }
      >
        {isLoading || error ? 'Files' : `Files · ${files.length}`}
      </SectionLabel>

      {isLoading && (
        <div className="flex flex-col gap-2 py-2">
          <Skeleton className="h-4 w-2/3 bg-fill-elevated" />
          <Skeleton className="h-4 w-1/2 bg-fill-elevated" />
        </div>
      )}

      {error && (
        <p role="alert" className="py-2 text-label-md text-critical">
          {error.message}
        </p>
      )}

      {!isLoading && !error && files.length === 0 && (
        <p className="py-2 text-label-md text-tertiary">
          Nothing in {displayName}’s workspace yet. Files an employee writes elsewhere on
          disk are not listed — Hermes records no author for a file.
        </p>
      )}

      <ul className="flex flex-col">
        {shown.map((file) => (
          <li key={file.path} className="flex items-center gap-3 py-2">
            {file.isDirectory ? (
              <FolderClosedIcon className="size-5 shrink-0 stroke-[1.125] text-secondary" />
            ) : (
              <FileTextIcon className="size-5 shrink-0 text-secondary" />
            )}
            <span className="min-w-0 flex-1 truncate text-label-md text-primary">
              {file.name}
            </span>
            <time
              dateTime={file.timeIso}
              className="shrink-0 text-label-xs text-tertiary"
            >
              {file.timeLabel}
            </time>
          </li>
        ))}
      </ul>
    </section>
  )
}
