import { extendTailwindMerge } from 'tailwind-merge';

/**
 * Custom font size classes defined in @theme
 */
const fontSizeClasses = [
  'display-md',
  'display-sm',
  'display-xs',
  'heading-2xl',
  'heading-xl',
  'heading-lg',
  'heading-md',
  'heading-sm',
  'heading-xs',
  'body-xl',
  'body-lg',
  'body-md',
  'body-sm',
  'body-xs',
  'label-2xl',
  'label-xl',
  'label-lg',
  'label-md',
  'label-sm',
  'label-xs',
  'markdown-h1',
  'markdown-h2',
  'markdown-h3',
  'markdown-h4',
  'markdown-h5',
  'markdown-h6',
  'markdown-body',
];

/**
 * Custom semantic text color classes
 */
const textColorClasses = [
  'primary',
  'disabled',
  'secondary',
  'secondary-disabled',
  'secondary-inverse',
  'secondary-inverse-disabled',
  'tertiary',
  'tertiary-disabled',
  'inverse',
  'inverse-disabled',
  'inverse-fixed',
  'inverse-fixed-disabled',
  'fixed',
  'fixed-disabled',
  'brand',
  'brand-hover',
  'brand-active',
  'brand-disabled',
  'fill-brand',
  'fill-brand-hover',
  'fill-brand-active',
  'fill-brand-disabled',
  'info',
  'info-hover',
  'info-active',
  'info-disabled',
  'success',
  'success-hover',
  'success-active',
  'success-disabled',
  'warning',
  'warning-hover',
  'warning-active',
  'warning-disabled',
  'critical',
  'critical-hover',
  'critical-active',
  'critical-disabled',
];

/**
 * Custom semantic background color classes
 */
const backgroundColorClasses = [
  'primary',
  'inverse',
  'surface',
  'surface-variant',
  'surface-inverse',
  'surface-secondary',
  'surface-secondary-variant',
  'surface-tertiary',
  'surface-tertiary-variant',
  'surface-brand',
  'surface-info',
  'surface-success',
  'surface-warning',
  'surface-critical',
  'surface-elevated',
  'fill',
  'fill-hover',
  'fill-active',
  'fill-disabled',
  'fill-variant',
  'fill-variant-hover',
  'fill-variant-active',
  'fill-variant-disabled',
  'fill-secondary',
  'fill-secondary-hover',
  'fill-secondary-active',
  'fill-secondary-disabled',
  'fill-secondary-variant',
  'fill-secondary-variant-hover',
  'fill-secondary-variant-active',
  'fill-secondary-variant-disabled',
  'fill-tertiary',
  'fill-tertiary-hover',
  'fill-tertiary-active',
  'fill-tertiary-disabled',
  'fill-tertiary-variant',
  'fill-tertiary-variant-hover',
  'fill-tertiary-variant-active',
  'fill-tertiary-variant-disabled',
  'fill-inverse',
  'fill-inverse-hover',
  'fill-inverse-active',
  'fill-inverse-disabled',
  'fill-elevated',
  'fill-elevated-hover',
  'fill-elevated-active',
  'fill-elevated-disabled',
  'fill-brand',
  'fill-brand-hover',
  'fill-brand-active',
  'fill-brand-disabled',
  'fill-brand-secondary',
  'fill-brand-secondary-hover',
  'fill-brand-secondary-active',
  'fill-brand-secondary-disabled',
  'fill-info',
  'fill-info-hover',
  'fill-info-active',
  'fill-info-disabled',
  'fill-success',
  'fill-success-hover',
  'fill-success-active',
  'fill-success-disabled',
  'fill-success-secondary',
  'fill-success-secondary-hover',
  'fill-success-secondary-active',
  'fill-success-secondary-disabled',
  'fill-warning',
  'fill-warning-hover',
  'fill-warning-active',
  'fill-warning-disabled',
  'fill-warning-secondary',
  'fill-warning-secondary-hover',
  'fill-warning-secondary-active',
  'fill-warning-secondary-disabled',
  'fill-critical',
  'fill-critical-hover',
  'fill-critical-active',
  'fill-critical-disabled',
  'fill-critical-secondary',
  'fill-critical-secondary-hover',
  'fill-critical-secondary-active',
  'fill-critical-secondary-disabled',
];

/**
 * Custom semantic border/ring color classes
 */
const borderColorClasses = [
  'primary',
  'primary-hover',
  'primary-focus',
  'primary-disabled',
  'secondary',
  'secondary-hover',
  'secondary-focus',
  'secondary-disabled',
  'tertiary',
  'tertiary-hover',
  'tertiary-focus',
  'tertiary-disabled',
  'inverse',
  'inverse-hover',
  'inverse-focus',
  'inverse-disabled',
  'elevated',
  'elevated-hover',
  'elevated-focus',
  'elevated-disabled',
  'brand',
  'brand-hover',
  'brand-focus',
  'brand-disabled',
  'brand-secondary',
  'brand-secondary-hover',
  'brand-secondary-focus',
  'brand-secondary-disabled',
  'info',
  'info-hover',
  'info-focus',
  'info-disabled',
  'success',
  'success-hover',
  'success-focus',
  'success-disabled',
  'warning',
  'warning-hover',
  'warning-focus',
  'warning-disabled',
  'critical',
  'critical-hover',
  'critical-focus',
  'critical-disabled',
];

export const customTwMerge = extendTailwindMerge({
  extend: {
    classGroups: {
      'font-size': [{ text: fontSizeClasses }],
      'text-color': [{ text: textColorClasses }],
      'bg-color': [{ bg: backgroundColorClasses }],
      'border-color': [{ border: borderColorClasses }],
      'ring-color': [{ ring: borderColorClasses }],
      'placeholder-color': [{ placeholder: textColorClasses }],
    },
  },
});
